services:
  postgres:
    image: postgres:latest
    container_name: adonis_postgres
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: adonis
      POSTGRES_DB: adonis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
