export enum EventCategory {
  Training = 'training',
  Workshop = 'workshop',
  Seminar = 'seminar',
  Webinar = 'webinar',
  Meetup = 'meetup',
  Conference = 'conference',
  Convention = 'convention',
  Summit = 'summit',
  Expo = 'expo',
  Fair = 'fair',
  Festival = 'festival',
  Concert = 'concert',
  Show = 'show',
  Performance = 'performance',
  Competition = 'competition',
  Game = 'game',
  Tournament = 'tournament',
}
